name: Report a Bug
title: ""
description: Report a bug, crash, or other issue in TF2 Classified
projects: []
labels:
  - Type - Bug
body:
  - type: dropdown
    id: dropdown-0
    attributes:
      label: Platform
      description: Which platform were you playing on?
      options:
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    id: input-1
    attributes:
      label: GPU
      description: What is your GPU?
      placeholder: (e.g. NVIDIA GeForce RTX 3080 Ti, Intel UHD Graphics 770)
    validations:
      required: false
  - type: textarea
    id: textarea-2
    attributes:
      label: Description
      description: Please describe your issue, using as much detail as you can.
    validations:
      required: true
  - type: checkboxes
    id: checkboxes-3
    attributes:
      label: Checklist
      options:
        - label: I confirm I have tested this issue without mods and confirm it still occurs
          required: true
        - label: I have searched existing issues and confirm this issue is new
          required: true
